name: Akaunting
package: lazycat.community.app.akaunting
version: 3.1.19
min_os_version: 1.3.8
description: Online Accounting Software
homepage: https://github.com/akaunting/akaunting
author: akaunting
application:
    subdomain: akaunting
    background_task: true
    public_path:
        - /
    routes:
        - /=http://akaunting:80/
services:
    akaunting:
        # akaunting/akaunting:3.1.19-v
        image: registry.lazycat.cloud/czyt/akaunting/akaunting:08ac12d4fd435042
        ontainer_name: akaunting
        environment:
 {{if .U.enable_custom_domain}}
            - APP_URL={{.U.custom_domain}}
{{else}}
            - APP_URL=https://{{.S.AppDomain}}
{{end}}
            - DB_HOST=akaunting_db
            - DB_DATABASE=akaunting
            - DB_PORT=3306

            # Change these to match env/db.env
            - DB_USERNAME=admin
            - DB_PASSWORD=akaunting_password

            # You should change this to a random string of three numbers or letters followed by an underscore
            - DB_PREFIX=lzc_

        depends_on:
            - akaunting_db

    akaunting_db:
        image: registry.lazycat.cloud/czyt/library/mariadb:ef81e8580aca17f5
        container_name: akaunting_db
        environment:
            - MYSQL_DATABASE=akaunting
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=akaunting_password
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        binds:
            - /lzcapp/var/db:/var/lib/mysql
        health_check:
            test:
                - CMD-SHELL
                - healthcheck.sh --connect --innodb_initialized
            start_period: 30s

locales:
    zh:
        name: "Akaunting"
        description: "一款免费、开源的在线会计软件"
    zh_CN:
        name: "Akaunting"
        description: "一款免费、开源的在线会计软件"
    en:
        name: "Akaunting"
        description: "Online accounting software. Manage your money. Get invoices paid. Track expenses."
